import { Language } from "@/contexts/LanguageContext";

// 공개 페이지(홈·구성원·논문)의 UI 문자열. 내부 도구는 한국어 고정이므로 여기만 관리한다.
const STRINGS = {
  ko: {
    home: {
      introFallback: "연구실 소개가 준비 중입니다.",
      professor: "지도교수",
      contact: "연락처",
      membersTitle: "구성원",
      membersDesc: "연구실 멤버를 소개합니다",
      pubsTitle: "논문",
      pubsDesc: "연구 성과와 출판물",
      loginTitle: "구성원 로그인",
      loginDesc: "일정·프로젝트·자료 공유",
    },
    members: {
      title: "구성원",
      subtitle: "EDCL 연구실 멤버를 소개합니다.",
      loading: "불러오는 중...",
      loadError: "구성원 정보를 불러오지 못했습니다.",
      empty: "공개된 구성원 프로필이 아직 없습니다.",
      emptyHint: "구성원은 로그인 후 설정 > 공개 프로필에서 등록할 수 있습니다.",
    },
    publications: {
      title: "논문",
      subtitle: "EDCL 연구실의 연구 성과와 출판물입니다.",
      loading: "불러오는 중...",
      loadError: "논문 목록을 불러오지 못했습니다.",
      empty: "등록된 논문이 아직 없습니다.",
    },
    auth: {
      email: "이메일",
      password: "비밀번호",
      or: "또는",
      continueGoogle: "Google로 계속하기",
      continueGithub: "GitHub로 계속하기",
      googleBusy: "Google 로그인 중...",
      githubBusy: "GitHub 로그인 중...",
      loginTitle: "로그인",
      loginSubtitle: "EDCL 연구실 계정으로 로그인하세요.",
      forgotPassword: "비밀번호를 잊으셨나요?",
      loginButton: "로그인",
      loggingIn: "로그인 중...",
      noAccount: "아직 계정이 없나요?",
      signupLink: "회원가입",
      signupTitle: "회원가입",
      signupSubtitle: "가입 후 관리자 승인이 필요합니다.",
      name: "이름",
      namePlaceholder: "홍길동",
      passwordPlaceholder: "6자 이상",
      passwordConfirm: "비밀번호 확인",
      passwordConfirmPlaceholder: "비밀번호 재입력",
      signupButton: "회원가입",
      signingUp: "가입 처리 중...",
      haveAccount: "이미 계정이 있나요?",
      loginLink: "로그인",
      resetTitle: "비밀번호 재설정",
      resetSubtitle: "가입한 이메일로 재설정 링크를 보내드립니다.",
      resetSent:
        "입력하신 주소로 재설정 메일을 발송했습니다. 받은편지함(스팸함 포함)을 확인해주세요.",
      backToLogin: "로그인으로 돌아가기",
      resetButton: "재설정 메일 보내기",
      sending: "발송 중...",
      remembered: "비밀번호가 기억나셨나요?",
      errInvalidCredential: "이메일 또는 비밀번호가 올바르지 않습니다.",
      errInvalidEmail: "이메일 형식이 올바르지 않습니다.",
      errTooMany: "로그인 시도가 너무 많습니다. 잠시 후 다시 시도해주세요.",
      errDisabled: "비활성화된 계정입니다. 관리자에게 문의하세요.",
      errNetwork: "네트워크 오류가 발생했습니다. 연결 상태를 확인해주세요.",
      errLoginFail: "로그인에 실패했습니다. 잠시 후 다시 시도해주세요.",
      errEmailInUse: "이미 사용 중인 이메일입니다.",
      errWeakPassword: "비밀번호가 너무 약합니다. 6자 이상으로 설정해주세요.",
      errSignupFail: "회원가입에 실패했습니다. 잠시 후 다시 시도해주세요.",
      errNameRequired: "이름을 입력해주세요.",
      errPwLength: "비밀번호는 6자 이상이어야 합니다.",
      errPwMismatch: "비밀번호 확인이 일치하지 않습니다.",
      errResetFail: "메일 발송에 실패했습니다. 잠시 후 다시 시도해주세요.",
      errPopupBlocked:
        "브라우저가 팝업을 차단했습니다. 팝업 허용 후 다시 시도해주세요.",
      errAccountExists:
        "이미 같은 이메일로 가입된 계정이 있습니다. 처음 가입했던 방법으로 로그인해주세요.",
      errUnauthorizedDomain: "허용되지 않은 도메인입니다. 관리자에게 문의하세요.",
      errSocialFail: "소셜 로그인에 실패했습니다. 잠시 후 다시 시도해주세요.",
    },
  },
  en: {
    home: {
      introFallback: "Lab introduction coming soon.",
      professor: "Advisor",
      contact: "Contact",
      membersTitle: "Members",
      membersDesc: "Meet our lab members",
      pubsTitle: "Publications",
      pubsDesc: "Research outcomes",
      loginTitle: "Member Login",
      loginDesc: "Schedules, projects & resources",
    },
    members: {
      title: "Members",
      subtitle: "Meet the members of EDCL Lab.",
      loading: "Loading...",
      loadError: "Failed to load member profiles.",
      empty: "No member profiles are public yet.",
      emptyHint: "Members can publish a profile from Settings after signing in.",
    },
    publications: {
      title: "Publications",
      subtitle: "Research outcomes and publications of EDCL Lab.",
      loading: "Loading...",
      loadError: "Failed to load publications.",
      empty: "No publications yet.",
    },
    auth: {
      email: "Email",
      password: "Password",
      or: "or",
      continueGoogle: "Continue with Google",
      continueGithub: "Continue with GitHub",
      googleBusy: "Signing in with Google...",
      githubBusy: "Signing in with GitHub...",
      loginTitle: "Log in",
      loginSubtitle: "Sign in with your EDCL Lab account.",
      forgotPassword: "Forgot password?",
      loginButton: "Log in",
      loggingIn: "Signing in...",
      noAccount: "Don't have an account?",
      signupLink: "Sign up",
      signupTitle: "Sign up",
      signupSubtitle: "Admin approval is required after signing up.",
      name: "Name",
      namePlaceholder: "Your name",
      passwordPlaceholder: "6+ characters",
      passwordConfirm: "Confirm password",
      passwordConfirmPlaceholder: "Re-enter password",
      signupButton: "Sign up",
      signingUp: "Signing up...",
      haveAccount: "Already have an account?",
      loginLink: "Log in",
      resetTitle: "Reset password",
      resetSubtitle: "We'll send a reset link to your email.",
      resetSent:
        "A reset email has been sent to the address you entered. Please check your inbox (including spam).",
      backToLogin: "Back to login",
      resetButton: "Send reset email",
      sending: "Sending...",
      remembered: "Remembered your password?",
      errInvalidCredential: "Incorrect email or password.",
      errInvalidEmail: "Please enter a valid email address.",
      errTooMany: "Too many attempts. Please try again later.",
      errDisabled: "This account has been disabled. Contact the admin.",
      errNetwork: "A network error occurred. Please check your connection.",
      errLoginFail: "Failed to sign in. Please try again later.",
      errEmailInUse: "This email is already in use.",
      errWeakPassword: "Password is too weak. Use at least 6 characters.",
      errSignupFail: "Failed to sign up. Please try again later.",
      errNameRequired: "Please enter your name.",
      errPwLength: "Password must be at least 6 characters.",
      errPwMismatch: "Passwords do not match.",
      errResetFail: "Failed to send the email. Please try again later.",
      errPopupBlocked:
        "Your browser blocked the popup. Allow popups and try again.",
      errAccountExists:
        "An account with this email already exists. Sign in with the method you used first.",
      errUnauthorizedDomain: "This domain is not authorized. Contact the admin.",
      errSocialFail: "Social sign-in failed. Please try again later.",
    },
  },
} as const;

export type AuthStrings = ReturnType<typeof publicStrings>["auth"];

export function publicStrings(lang: Language) {
  return STRINGS[lang];
}
